### ISSUE TITLE
Support @@cfg within module & signatures

### ISSUE THREAD

**Issue by leostera** [leostera/config.ml#3]
Right now we can't use `@cfg` in elements defined within modules and signatures.

The expected behavior is that `@cfg` can be used in places like this:

```ocaml
module A : sig
 val a : unit -> unit [@@cfg disable = true]
end =
 let a () = () [@@cfg disable = true]
end
```

and interface files:

```ocaml
module A : sig
 val a : unit -> unit [@@cfg disable = true]
end
```

**Comment by KFoxder** [comment]
@leostera you can assign this to me. I am going to put something out for it.

**Comment by KFoxder** [comment]
@leostera this can be closed now I think
