### ISSUE TITLE
Support @@cfg in function branches

### ISSUE THREAD

**Issue by leostera** [leostera/config.ml#4]
Currently, this is unsupported:

```ocaml
let foo a = function
  | 0 -> "0"
  | 1 -> "1"
  [@@cfg (disable=true)]
```

And the expected behavior is that we can remove that function branch with the annotation.

**Comment by KFoxder** [comment]
This will get addressed in https://github.com/ocaml-sys/config.ml/pull/13. @leostera you can assign this to me.

**Comment by KFoxder** [comment]
@leostera I think this too can be closed now
