### ISSUE TITLE
Support @@cfg in match cases

### ISSUE THREAD

**Issue by leostera** [leostera/config.ml#5]
Currently, this is unsupported:

```ocaml
let foo a =
  match a with
  | 0 -> "0"
  | 1 -> "1"
  [@@cfg (disable=true)]
```

And the expected behavior is that we can remove that match case with the annotation.

This is mostly important for having good support for conditional constructors and variants, so that we can disable in tandem the pattern matching branches for them.

**Comment by KFoxder** [comment]
I am planning to look at this during the week.

**Comment by leostera** [comment]
Sounds great! ✨ Let us know if we can help :) and feel free to open a draft PR if you want some early feedback. Thanks! 🙏🏼

**Comment by KFoxder** [comment]
@leostera I think we can close this now!
